---
# tasks file for haproxy
- name: http
  package:
    name: httpie
    state: latest
  notify: restart_HAProxy

- name: install HAProxy
  yum:
    name: haproxy 
    state: latest
  notify: restart_HAProxy
   
#- name: enable HAProxy
#  service:
#    name: haproxy
#    state: started

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_HAProxy

#- name: restart_HAProxy
#  service:
#    name: haproxy
#    state: restarted
